### ISSUE TITLE
Push new release to PyPI

### ISSUE THREAD

**Issue by jacobh** [gizmag/django-fsm-log#32]
should get around to this sometime soon.

Interested in doing this @dinie? just saw you pushing releases for something else :)

**Comment by browniebroke** [comment]
Are you guys expecting some progress on this or you're not using/maintaining this package anymore? 

Have you considered automating it [with Travis](https://docs.travis-ci.com/user/deployment/pypi/) to help the maintenance? I usually add conditions below to restrict when releases are done:

```yaml
deploy:
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    condition: "$TOX_ENV = py27-dj-1.8"
```

Thanks 😄
